### PR TITLE
Preserve folder structure of input files [Published Fork on NPM]

### PR DESCRIPTION
**Pull request by stfsy**
### Published my fork here: https://www.npmjs.com/package/image-2-min

Feel free to use that one 😃 

_____________

Came across the same problem as @djforth in #191 #192. Thought it would be a good idea to be able to call **globby** with a configurable cwd and changed the resolution of the input and output paths.

Files are now read from

``` javascript
path.join(opts.cwd, input)
```

and written to

``` javascript
path.join(output, input)
```
### Directory structure

```
test
└─── fixtures
│   │   fixture.jpg
│   │   fixture.1.jpg
│   └─── folder
│         │   fixture.jpg
```
## Testcases

``` javascript
test('output the file in {temp}', async t => {
    const files = await m(['**/*.jpg'], tmp, {plugins: imageminJpegtran(), cwd: 'fixtures/folder'});

    t.is(files.length, 1);
    t.is(files[0].path, path.join(tmp, 'fixture.jpg'));
});
```

``` javascript
test('output the file in {temp}/folder', async t => {
    const files = await m(['folder/**/*.jpg'], tmp, {plugins: imageminJpegtran(), cwd: 'fixtures'});

    t.is(files.length, 1);
    t.is(files[0].path, path.join(tmp, 'folder', 'fixture.jpg'));
});
```

``` javascript
test('output the file in {temp}/fixtures/folder', async t => {
    const files = await m(['fixtures/folder/**/*.jpg'], tmp, {plugins: imageminJpegtran()});

    t.is(files.length, 1);
    t.is(files[0].path, path.join(tmp, 'fixtures', 'folder', 'fixture.jpg'));
});
```

### CODE REVIEW

**Comment by mtrules** [comment]
Thank you for this fix.

**Comment by antgonzales** [comment]
It's been more than a year on this issue, any chance it will make it to next release?

**Comment by kevva** [comment]
@antgonzales, yes. I'm currently reviewing it.

**Comment by reedling78** [comment]
Sure be nice if this option would be merged in. I tried it locally and it seems to work fine.

**Comment by stfsy** [comment]
allright.. @reedling78 @antgonzales @mtrules  i published my fork here https://www.npmjs.com/package/image-2-min

**Comment by aurelienlewin** [comment]
So what?

**Comment by antgonzales** [comment]
@stfsy I don't recall what I originally did, I also left the company where I came up with a solution, but I don't think a fork is the way to go. I think a better solution would be to write a gist that we could include in the documentation that shows how to create the behavior we want by leveraging node's api.

I don't have time at the moment right now, but I'll put it on my ticker to write something up. Feel free to write up a gist though if you have time.

**Comment by stfsy** [comment]
@antgonzales no, it's definitely **not** the way to go. i'd be willing to create a new pull request based on your master branch with my original changes and tests, but only if you are ready to merge it^^. that's imho the way to go.

**Comment by antgonzales** [comment]
@stfsy ehhh I'm confused. I don't have a master branch. This isn't my project.

**Comment by chesscai** [comment]
My Fork [imagemin-keep-folder](https://github.com/chesscai/imagemin-keep-folder) form [imagemin](https://github.com/imagemin).

> support keep and customize folder structure

## Install

```
$ npm install --save-dev imagemin-keep-folder
```

## Usage

```js
// as usual
const imagemin = require('imagemin-keep-folder');

imagemin(['images/*.{jpg,png}'], 'build/images', {
	
}).then(files => {
	console.log(files);
	//=> [{data: <Buffer 89 50 4e …>, path: 'build/images/foo.jpg'}, …]
});
```

```js
// keep folder structure as input
const imagemin = require('imagemin-keep-folder');

imagemin(['images/**/*.{jpg,png}'], {
  
});
// for example
// images/a.jpg => images/a.jpg
// images/foo/a.jpg => images/foo/a.jpg
// images/foo/bar/a.jpg => images/foo/bar/a.jpg
```

```js
// keep folder structure as input use imagemin-webp
const imagemin = require('imagemin-keep-folder');
const imageminWebp = require("imagemin-webp");

imagemin(['images/**/*.{jpg,png}'], {
  use: [
    imageminWebp({})
  ]
});
// for example
// images/a.jpg => images/a.webp
// images/foo/a.jpg => images/foo/a.webp
// images/foo/bar/a.jpg => images/foo/bar/a.webp
```

```js
// customize folder structure as input use imagemin-webp
const imagemin = require('imagemin-keep-folder');
const imageminWebp = require("imagemin-webp");

imagemin(['images/**/*.{jpg,png}'], {
  use: [
    imageminWebp({})
  ],
  replaceOutputDir: output => {
    return output.replace(/images\//, '.webp/')
  }
});
// for example
// images/a.jpg => .webp/a.webp
// images/foo/a.jpg => .webp/foo/a.webp
// images/foo/bar/a.jpg => .webp/foo/bar/a.webp
```

**Pull request closed without merging**
