### PR TITLE
add folder structure from input to output

### PR DESCRIPTION
**Pull request by djforth**
I specified the issue here - https://github.com/imagemin/imagemin/issues/191

Basically the folder structure from your input was not matching your output.  So I've put a fix to make sure any folders in your glob will be replicated in your output

e.g. input/foo/bar/my-img.jpg -> output/foo/bar/my-img.jpg

### CODE REVIEW

**Comment by djforth** [comment]
Hmm looks like it's failing on windows path, not sure if it's my test or my code.  Not a window's guys so not sure why the paths are not working?

**Comment by theskillwithin** [comment]
this isn't added yet?

**Comment by jeffkamo** [comment]
What is the status of this fix?

**Comment by coder77** [comment]
@djforth What is the status of this fix? Need it badly.

**Comment by sindresorhus** [comment]
Closing for lack of activity. I also don't think this is the correct approach.

**Comment by joelpittet** [comment]
@sindresorhus what is the right approach?

**Pull request closed without merging**
