### PR TITLE
Keep folder structure

### LINKED ISSUE #191: Output ignores input folder structure
Think this may be related to https://github.com/imagemin/imagemin/issues/87.

If I put an input destination on /imgs/**/*.{*.png, *.gif, *.jpg, *.svg} and set my destination too /build/imgs then I would expect:

/imgs/foo/bar.jpg -> /build/imgs/foo/bar.jpg

but is actually creating it as:

/imgs/foo/bar.jpg -> /build/imgs/bar.jpg

### PR DESCRIPTION
**Pull request by rhengles**
Fixes #191 

Adds a new option, `basedir` from which all inputs and outputs are calculated. The folder structure after `basedir` is preserved.

There is also an additional option, `outputPath` which can be used to customize the output path even further.

### CODE REVIEW

**Comment by aurelienlewin** [comment]
Any update?

**Comment by lf-jeremy** [comment]
@rhengles I really look forward to using the new `basedir` option your pull request adds.

Your changes are failing tests due to code linting rules. It looks like changing `let` to `const` for your two `rel` variable definitions will get your builds to pass. It would be great to see your pull request accepted by the project maintainers.

**Comment by sindresorhus** [comment]
We welcome a way to preserve folder structure, but it should be more thought out than this, and it should be well tested and documented.

**Comment by rhengles** [comment]
I respect your opinion, but I don't understand what is poorly thought out about this implementation.

Would appreciate further clarifications beyond "tests and documentation."

**Comment by rhengles** [comment]
@sindresorhus Just a heads up, maybe this was forgotten.

I'd like to know how the implementation could be improved, to avoid wasted effort on "tests and documentation."

Thanks 😊

**Comment by rhengles** [comment]
@sindresorhus up?

**Comment by rhengles** [comment]
@sindresorhus Here's the monthly bump. I really want to understand what is poorly thought out here.

The user can provide the `basedir` option, from which all subfolders are kept, **OR** can provide a `outputPath` option, which is a `function(input, output, options, meta)` so the user can provide a completely custom path to each file processed.

The user can store arbitrary data in the `meta` object, which is sent to each plugin so the data can be used in the plugins.

**Comment by rhengles** [comment]
@sindresorhus up

**Comment by rhengles** [comment]
@sindresorhus up

**Comment by markadrake** [comment]
> We welcome a way to preserve folder structure, but it should be more thought out than this, and it should be well tested and documented.

@sindresorhus could you please give this issue some attention? The community has been trying to solve this issue since 2017, and such a simple feature as respecting the folder structure when running it against a huge library of images is absolutely necessary. Many of us have made forks due to this one missing feature.

Could you please give us more feedback as to how this PR did not meet expectations, and what we can do to move this along? Or, if you indisposed at the moment, could @kevva or @bradbaris or @1000ch please help?

**Pull request closed without merging**
