### PR TITLE
Included a cwd option to retain folder structure when minifying.

### PR DESCRIPTION
**Pull request by yeongkongpoh**
**Current problem:**
Output destinations are not following source structure, it is flatten accordingly to the user's defined destination. 

**Solution applied:**
Added a cwd option to identify the correct working path, cwd value will represent the path we need to remove from the glob pattern determined by the user. 

The reformatted path will then be prepended by the destination. 

I've tried not to alter too much but to keep with the original flow of the process. 

**Todo:**
If pull request is approved, to add cwd option to README.

**Priority:**
Urgent

**Reason:**
As a web developer myself, I depend on useful tools like this to get by my daily development. I believe by adding this request, it can help improve development workflows better.

### CODE REVIEW

**Comment by markadrake** [comment]
Changes look good but I had some trouble after implementation. I had to make an additional change, appending the `path.sep` just before the concatenation of `path.basename(input)`. Could you review your PR to make sure it works with paths many folders deep? This is what the change I made looks like:

```
const inputSrc = opts.cwd ? path.dirname(input).replace(opts.cwd, '') + path.sep + path.basename(input) : path.basename(input);
const dest = output ? path.join(output, inputSrc) : null;
```

**Comment by g4mbit** [comment]
@markadrake My apologies on such a late reply, I think I can put together @Ser-Gen changes and do some test cases before we merge this PR. 

Another alternative is that we use #196 instead. 

What say everyone?

**Comment by olhapi** [comment]
For Christ's sake, finish and merge this pull request, please. So many devs need this feature.

**Comment by kdelmonte** [comment]
Any news on when this will be released?

**Comment by sindresorhus** [comment]
We welcome a way to preserve folder structure, but it should be more thought out than this, and it should be well tested and documented.

**Pull request closed without merging**
